name:  Mule_Service1_Build_Deploy
on:
  repository_dispatch:
    types: 
      - Service1-Mule
  workflow_dispatch:
permissions:
    contents: write
    packages: write
    actions: write
    id-token: write
jobs: 
  Service1_Deploy:
     name: Mule-Build-Deploy
     uses: shiyamsundark/DevOpsCommon-Mule/.github/workflows/Build_Deploy.yml@main
     with:
       Repository: ${{ github.repository }}
