name:  Mule_Service1_Build_Deploy
on:
  repository_dispatch:
    types: 
      - Service1-Mule
  workflow_dispatch:
permissions:
    contents: write
    packages: write
    actions: write
    id-token: write
jobs: 
  Set_Input_Variables:
    runs-on: ubuntu-latest
    steps:
      - env:
          Repository: ${{ github.event.client_payload.message }} 
          Version: ${{ github.event.client_payload.Version }}
        run: |
             echo $Version
             echo $Repository
        
  Service1_Deploy:
     name: Mule-Build-Deploy
     uses: shiyamsundark/DevOpsCommon-Mule/.github/workflows/Build_Deploy.yml@main
     with:
       Repository: ${{ github.repository }}
