name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:
  
env:
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
      SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
      SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and deploy artifact to sandbox
        run: mvn -B deploy
      
