name: Sandbox/Mulesoft - Build and Deploy

# on: 
#   workflow_dispatch:
  
     
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
        
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
          
#       - name: Build with Maven
#         run: mvn -B package --file pom.xml
        
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v3
#         - uses: actions/setup-java@v3
#           with:
#               java-version: '11'
#               distribution: 'adopt'
              
#         - name: Publish package
        
#           env:
          
#             PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
#             PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
            
#           run: mvn clean package deploy -DmuleDeploy

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:   
    - uses: actions/checkout@v2    
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
       
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
 
    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2 
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    
    - name: Deploy to Sandbox
      env:
            PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
            PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
            run: |
             mvn deploy -DmuleDeploy \-Dmule.artifact=$artifactName \
             -Danypoint.username="$PLATFORM_USERNAME" \
             -Danypoint.password="$PLATFORM_PASSWORD" \
             -DskipTests
        
        
      
