name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:

env:
          
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     
jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
        
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
          
#       - name: Build with Maven
#         run: mvn -B package --file pom.xml
        
 Sonar:
    
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Sonar Analysis
        run: mvn -B verify sonar:sonar
        
#   deploy:
#     needs: [build,Sonar]
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v3
#         - uses: actions/setup-java@v3
#           with:
#               java-version: '11'
#               distribution: 'adopt'
              
#         - name: Publish package
        
#           run: |
      
#            mvn deploy -DmuleDeploy \
#            -Dmule.artifact=$artifactName \
#            -Danypoint.username="$USERNAME" \
#            -Danypoint.password="$PASSWORD" \
#            -DskipTests

        
      
