name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:

env:
          
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
  Sonar:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Sonar Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=shiyamsundark_hello-world-mule-lab -Dsonar.organization=shiyamsundark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        
  Deploy:
    needs: [Build,Sonar]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Deploy package
        
          run: |
      
           mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="$USERNAME" \
           -Danypoint.password="$PASSWORD" \
           -DskipTests

  Publish:
   
       needs: [Build,Sonar,Deploy]
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          
          - name: Publish to GitHub Packages Apache Maven
            run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      
