name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:

env:
          
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
#   Sonar:
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:   
#       - name: Sonar Analysis
#         run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=shiyamsundark_hello-world-mule-lab -Dsonar.organization=shiyamsundark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN --file pom.xml
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Deploy package
        
          run: |
      
           mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="$USERNAME" \
           -Danypoint.password="$PASSWORD" \
           -DskipTests
           
  Publish:
   
       needs: [build,deploy]
       runs-on: ubuntu-latest
       permissions:
        contents: read
        packages: write
       steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
      
          - name: Publish to GitHub Packages Apache Maven
            run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
            
        
      
