name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:

env:
          
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     
jobs:

#   Pre-Release:
#     name: Pre-Release
#     runs-on: ubuntu-latest
#     outputs:
#       versn: ${{ steps.versnid.outputs.versn }}
#     steps:
#       - uses: actions/checkout@v2
#       - id: versnid
#         run: |
#           echo setting release version!!
#           aws s3 cp s3://instidbucket/version/versionnew.cfg ${{ github.workspace }}/versions.cfg --region us-west-1  
#           echo "${{ github.run_number }}" >> versions.cfg
#           newversion=$(cat versions.cfg)
#           echo $newversion
#           echo "::set-output name=versn::$newversion"
    
  Build:
       
       runs-on: ubuntu-latest
       permissions:
        contents: read
        packages: write
       steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
              server-id: github 
              settings-path: ${{ github.workspace }} 
              
          - name: Build with Maven
            run: mvn -B package --file pom.xml

          - name: Publish to GitHub Packages Apache Maven
            run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
  Sonar:
  
    needs: [Build]
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Sonar Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=shiyamsundark_hello-world-mule-lab -Dsonar.organization=shiyamsundark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        
  Deploy:
  
    needs: [Build,Sonar]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Deploy to Sandbox
        
          run: |
      
           mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="$USERNAME" \
           -Danypoint.password="$PASSWORD" \
           -DskipTests

