name: Post-Release
on: 
  workflow_call:
   
jobs:
    Post-Release:
      runs-on: ubuntu-latest
      steps:    
        - name: Post Release Task
          run: |
            echo Update Versioning Repo!!
